from __future__ import annotations

import hashlib
import json
from pathlib import Path

import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageEnhance, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent / "ocr_fixtures"
BASE_SIZE = (1200, 850)
GROUND_TRUTH = """SCAN2SHEET TEST INVOICE
GSTIN: 27ABCDE1234F1Z5
Invoice No: INV-102
Date: 12/04/2025
Taxable Amount: 10000.00
CGST: 900.00
SGST: 900.00
Grand Total: 11800.00"""
FIELDS = {
    "gstin": "27ABCDE1234F1Z5",
    "invoice_number": "INV-102",
    "date": "12/04/2025",
    "taxable_amount": "10000.00",
    "cgst": "900.00",
    "sgst": "900.00",
    "total": "11800.00",
}


def _font(size: int) -> ImageFont.FreeTypeFont:
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
    ]
    for path in candidates:
        if Path(path).exists():
            return ImageFont.truetype(path, size)
    raise RuntimeError("A deterministic TrueType font is required to generate OCR fixtures.")


def base_document(text_fill=(20, 20, 20), background=(250, 250, 247)) -> Image.Image:
    image = Image.new("RGB", BASE_SIZE, background)
    draw = ImageDraw.Draw(image)
    draw.rectangle((55, 45, 1145, 805), outline=(90, 90, 90), width=3)
    draw.text((90, 80), "SCAN2SHEET TEST INVOICE", font=_font(42), fill=text_fill)
    draw.line((90, 150, 1110, 150), fill=(120, 120, 120), width=2)
    lines = [
        "GSTIN: 27ABCDE1234F1Z5",
        "Invoice No: INV-102",
        "Date: 12/04/2025",
        "Taxable Amount: 10000.00",
        "CGST: 900.00",
        "SGST: 900.00",
        "Grand Total: 11800.00",
    ]
    for index, line in enumerate(lines):
        draw.text((105, 200 + index * 78), line, font=_font(38), fill=text_fill)
    return image


def save(category: str, image: Image.Image, notes: str) -> dict[str, object]:
    directory = ROOT / category
    directory.mkdir(parents=True, exist_ok=True)
    if category == "phone_photo":
        path = directory / "invoice_01.jpg"
        image.save(path, format="JPEG", quality=88, subsampling=0, optimize=True)
    else:
        path = directory / "invoice_01.png"
        image.save(path, format="PNG", compress_level=9)
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return {
        "fixture": f"{category}/{path.name}",
        "category": category,
        "sha256": digest,
        "ground_truth_text": GROUND_TRUTH,
        "important_fields": FIELDS,
        "reviewed": True,
        "provenance": "Synthetic public fixture generated by tests/generate_ocr_fixtures.py; contains no client or confidential data.",
        "degradation": notes,
    }


def make_phone_photo(image: Image.Image) -> Image.Image:
    src = np.array(image.convert("RGB"))
    h, w = src.shape[:2]
    src_pts = np.float32([[0, 0], [w - 1, 0], [w - 1, h - 1], [0, h - 1]])
    dst_pts = np.float32([[70, 45], [w - 55, 10], [w - 10, h - 50], [35, h - 5]])
    matrix = cv2.getPerspectiveTransform(src_pts, dst_pts)
    warped = cv2.warpPerspective(src, matrix, (w, h), borderValue=(238, 238, 232))

    yy, xx = np.mgrid[0:h, 0:w]
    lighting = 0.70 + 0.30 * (xx / max(1, w - 1))
    vignette = 1.0 - 0.10 * (((xx - w / 2) / (w / 2)) ** 2 + ((yy - h / 2) / (h / 2)) ** 2)
    scale = np.clip(lighting * vignette, 0.58, 1.0)[..., None]
    shaded = np.clip(warped.astype(np.float32) * scale, 0, 255).astype(np.uint8)

    rng = np.random.default_rng(20260919)
    noise = rng.normal(0, 5, shaded.shape).astype(np.int16)
    noisy = np.clip(shaded.astype(np.int16) + noise, 0, 255).astype(np.uint8)
    return Image.fromarray(noisy, mode="RGB")


def ensure_fixtures() -> None:
    manifest_path = ROOT / "manifest.json"
    if not manifest_path.exists():
        main()
        return
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    if any(not (ROOT / item["fixture"]).exists() for item in payload.get("fixtures", [])):
        main()


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    clean = base_document()
    manifest: list[dict[str, object]] = []
    manifest.append(save("clean", clean, "No degradation; clean non-regression control."))
    manifest.append(save("rotated", clean.rotate(90, expand=True, fillcolor=(250, 250, 247)), "90 degree coarse rotation."))
    manifest.append(save("skewed", clean.rotate(9.0, expand=True, fillcolor=(250, 250, 247)), "+9 degree skew."))

    low = base_document(text_fill=(190, 190, 190), background=(226, 226, 222))
    low = ImageEnhance.Contrast(low).enhance(0.45)
    manifest.append(save("low_contrast", low, "Compressed foreground/background intensity separation."))

    rng = np.random.default_rng(20260919)
    arr = np.array(clean)
    mask = rng.random(arr.shape[:2])
    noisy_arr = arr.copy()
    noisy_arr[mask < 0.012] = 0
    noisy_arr[mask > 0.988] = 255
    manifest.append(save("noisy", Image.fromarray(noisy_arr), "Deterministic salt-and-pepper noise, seed 20260919."))

    blurred = clean.filter(ImageFilter.GaussianBlur(radius=3.0))
    manifest.append(save("blurred", blurred, "Severe Gaussian blur radius 3.0."))
    manifest.append(save("phone_photo", make_phone_photo(clean), "Perspective warp, uneven illumination, vignette and deterministic sensor-like noise."))

    payload = {
        "schema": 1,
        "review_status": "manually-verified-synthetic-ground-truth",
        "generator": "tests/generate_ocr_fixtures.py",
        "fixtures": manifest,
    }
    (ROOT / "manifest.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
